version: '2'

services:

  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: '-------------'
      POSTGRES_PASSWORD: '--------------'
      POSTGRES_DB: '----------'

  compression:
    build: ./compression_server
    # image: compression
    environment:

      AWS_JAMRECORD_ACCESS_KEY_ID: '----------'
      AWS_JAMRECORD_SECRET_ACCESS_KEY: '-------------'
      AWS_JAMRECORD_REGION: '---------'
      AWS_JAMRECORD_BUCKET: '--------'

      JAMRECORD_PRIMARY_SERVER: 'http://localhost:3000'

      PORT: 4000

    ports:
      - "4000:4000"
  
  primary:
    build: .
    links:
      - db
      - compression
    ports:
      - "3000:3000"
    environment:
      
      JAMRUN: 'production'

      AWS_JAMRECORD_ACCESS_KEY_ID: '----------'
      AWS_JAMRECORD_SECRET_ACCESS_KEY: '---------------'
      AWS_JAMRECORD_REGION: '----------------'
      AWS_JAMRECORD_BUCKET: '------------'

      JAMRECORD_PORT: '3000'
      JAMRECORD_PRIMARY_SERVER: 'http://localhost:3000'

      JAMRECORD_JWT_SECRET: '--------------'
      JAMRECORD_MAILGUN_API_KEY: '-------------'
      JAMRECORD_MAILGUN_DOMAIN: '---------------'
      COMPRESSION_SERVER: 'http://localhost:4000'

      SEQ_DB: '--------------'
      SEQ_USER: '-------------'
      SEQ_PW: '------------'
      PORT: 3000
      JAMRECORD_PRODUCTION_CONNECTION_STRING: 'postgres://---------:-------------@db:5432/-----------'
      COMPRESSION_SERVER: 'http://compression:4000'
